# Generated by Selenium IDE
import shelve
from time import sleep

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By


class TestDemo():
    """
    该模块用于获取企业微信登录cookie并通过shelve存储到cookies.db文件
    """
    def setup_method(self, method):
        options = Options()
        options.debugger_address = "127.0.0.1:9222"
        # 复用模式
        self.driver = webdriver.Chrome('/Users/apple/Documents/web/chromedriver', options=options)
        # self.driver = webdriver.Chrome('/Users/apple/Documents/web/chromedriver')
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_demo(self):
        # self.driver.get('https://ceshiren.com/')
        # self.driver.find_element_by_link_text("未读（4）").click()
        # 处于哪个页面就获取哪个页面cookies
        # print(self.driver.get_cookies())
        # 获取cookies前要访问网页
        # cookies = self.driver.get_cookies()
        # cookies = [{'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'ww_rtkey', 'path': '/', 'secure': True,
        #             'value': '3655319596'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.logined', 'path': '/',
        #             'secure': True, 'value': 'true'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.vid', 'path': '/',
        #             'secure': True, 'value': '1688852026634893'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.vid', 'path': '/',
        #             'secure': True, 'value': '1688852026634893'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ltype', 'path': '/',
        #             'secure': True, 'value': '1'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.d2st', 'path': '/',
        #             'secure': True, 'value': 'a5202664'},
        #            {'domain': '.qq.com', 'expiry': 1592551664, 'httpOnly': False, 'name': '_gid', 'path': '/',
        #             'secure': False, 'value': 'GA1.2.1798085393.1592461189'},
        #            {'domain': 'work.weixin.qq.com', 'httpOnly': True, 'name': 'ww_rtkey', 'path': '/', 'secure': False,
        #             'value': '3655319596'},
        #            {'domain': '.qq.com', 'expiry': 2147385600, 'httpOnly': False, 'name': 'pgv_pvid', 'path': '/',
        #             'secure': True, 'value': '5923305596'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.refid', 'path': '/',
        #             'secure': True, 'value': '2001293180981182'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ref', 'path': '/', 'secure': True,
        #             'value': 'direct'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.sid', 'path': '/', 'secure': True,
        #             'value': 'Un0tIFo2Whjn4NA1dl7fJkolB42Ldhhlkp-K3m2tbRZXBZDUSIs87VQRWcI9x_Qd'},
        #            {'domain': '.qq.com', 'httpOnly': False, 'name': 'pgv_info', 'path': '/', 'secure': True,
        #             'value': 'ssid=s1002332439'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.vst', 'path': '/', 'secure': True,
        #             'value': 'z0k6oh-JL8VB8R2leFFvad62jnchFqo81o3pnzjtuzxu3GRkYq8RqM5JTG-PAAPn2R81m0v7BE7hICtVn3bsGUBBNKJasPznvokVY6v5CXuCZKVPFChDSi8RR9AGrEoG-vurQQ9sOiyJsDfbYuSoc7SkVoM6iu_bysJOUMoz4-CAUe9ny5NidwmTb5IcscqDqAFGxXgMHU_QcYzR-PlE4ssCyvWl3lqg95UdXtjns_EOOrtInmoLxUOroguAUEm3FqWvJ59wmQlgocS1ZCovAQ'},
        #            {'domain': '.qq.com', 'expiry': 1655537264, 'httpOnly': False, 'name': '_ga', 'path': '/',
        #             'secure': False, 'value': 'GA1.2.536663283.1592461189'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': False,
        #             'name': 'Hm_lpvt_9364e629af24cb52acc78b43e8c9f77d', 'path': '/', 'secure': True,
        #             'value': '1592464583'},
        #            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.corpid', 'path': '/',
        #             'secure': True, 'value': '1970325140138289'},
        #            {'domain': '.work.weixin.qq.com', 'expiry': 1624000583, 'httpOnly': False,
        #             'name': 'Hm_lvt_9364e629af24cb52acc78b43e8c9f77d', 'path': '/', 'secure': True,
        #             'value': '1592461249,1592461389,1592463188,1592464583'},
        #            {'domain': '.work.weixin.qq.com', 'expiry': 1595057266, 'httpOnly': False, 'name': 'wwrtx.i18n_lan',
        #             'path': '/', 'secure': False, 'value': 'zh'}]

        # 为任何页面添加cookie
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        # 1 首先打开复用模式访问企业微信(已登录状态) 通过db['cookie'] = self.driver.get_cookies() 将cookies存储在shelve中
        # 2 关闭复用模式  通过db = shelve.open('cookies') 读取cookies
        # 3 将cookies添加到指定的url访问地址中，实现跳过登录访问登录
        db = shelve.open('cookies')
        db['cookie'] = self.driver.get_cookies()
        # db = shelve.open('cookies')
        # cookies = db['cookie']
        # for cookie in cookies:
        #     if 'expiry' in cookie.keys():
        #         cookie.pop("expiry")
        #     self.driver.add_cookie(cookie)
        # self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        # sleep(3)
        # self.driver.find_element_by_id('menu_contacts').click()
        # sleep(3)
        # db.close()
